### ISSUE TITLE
Support dark mode on MacOS Mojave

### ISSUE THREAD

**Issue by sambeevors** [sambeevors/sambeevors.com#57]
Example:
```css
@media (prefers-color-scheme: dark) {
  body {
    color: #fff;
    background-color: #222;
  }
}
```
